### ISSUE TITLE
ESP monster board to buy

### ISSUE THREAD

**Issue by zhivko** [kodera2t/ESP32_OLED_LAN8720_sample#1]
Is it possible to purchase ESP32 Monsterboard somewhere?
Link to page?
Maybe you can sell some of the boards?

**Comment by kodera2t** [comment]
You can find several information here
https://www.tindie.com/products/microwavemont/esp32-monster-board-ether-can-oled-all-in-one/
and
https://hackaday.io/project/21321-esp32-monster-board
Thank you for interest!
